#!/bin/bash

PROJECT=library

CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o lxcfs-admission-webhook
docker build --no-cache -t local.harbor.io/${PROJECT}/lxcfs-admission-webhook:v1 .
rm -rf lxcfs-admission-webhook

docker push local.harbor.io/${PROJECT}/lxcfs-admission-webhook:v1
