apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-lxcfs-admission-webhook-cfg
  labels:
    app: lxcfs-admission-webhook
webhooks:
  - name: validation.lxcfs-admission-webhook.alcor.io
    clientConfig:
      service:
        name: lxcfs-admission-webhook-svc
        namespace: kube-system
        path: "/validate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["pod", ""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        lxcfs-admission-webhook: enabled
